[package]
name = "fedimint-gateway-cli"
version = "0.3.0-alpha"
edition = "2021"
license = "MIT"
description = "CLI tool to control lightning gateway"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gateway-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.64"
axum = "0.6.4"
axum-macros = "0.3.1"
bitcoin = { version = "0.30.2", features = ["serde"] }
clap = { version = "4.1.6", features = ["derive", "std", "help", "usage", "error-context", "suggestions"], default-features = false }
ln-gateway = { version = "0.3.0-alpha", package = "fedimint-ln-gateway", path= "../ln-gateway" }
fedimint-core = { version = "0.3.0-alpha", path = "../../fedimint-core" }
fedimint-logging = { version = "0.3.0-alpha", path = "../../fedimint-logging" }
reqwest = { version = "0.11.14", features = [ "json", "rustls-tls" ], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
tokio = {version = "1.26", features = ["full"]}
tracing = { version = "0.1.37", default-features = false, features= ["log", "attributes", "std"] }
url = { version = "2.3.1", features = ["serde"] }
clap_complete = "4.3.1"

[build-dependencies]
fedimint-build = { version = "0.3.0-alpha", path = "../../fedimint-build" }
