[package]
name = "fedimint-bitcoind"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Bitcoin Core connectivity used by Fedimint"
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_bitcoind"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
bitcoin = "0.30.2"
bitcoin_hashes = "0.12.0"
bitcoincore-rpc = { version = "0.17.0", optional = true }
electrum-client = {version = "0.18.0", optional = true }
esplora-client = { version = "0.6.0", default-features = false, features = ["async", "async-https-rustls"], optional = true }
lazy_static = "1.4.0"
fedimint-core  = { version = "0.3.0-alpha", path = "../fedimint-core" }
fedimint-logging = { version = "0.3.0-alpha", path = "../fedimint-logging" }
rand = "0.8"
hex = { version = "0.4.3", features = [ "serde"] }
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
tracing = "0.1.37"
url = "2.3.1"

[features]
default = ["bitcoincore-rpc", "electrum-client", "esplora-client"]
