[package]
name = "fedimint-load-test-tool"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-load-test-tool is a tool to load test the fedimint server and gateway."
license = "MIT"
publish = false

[[bin]]
name = "fedimint-load-test-tool"
path = "src/main.rs"

[dependencies]
anyhow = "1"
base64 = "0.20.0"
bitcoin = "0.30.2"
clap = { version = "4.1.6", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env" ], default-features = false }
devimint = { version = "0.3.0-alpha", path = "../devimint" }
fedimint-client = { version = "0.3.0-alpha", path = "../fedimint-client" }
fedimint-core = { version = "0.3.0-alpha", path = "../fedimint-core" }
fedimint-ln-client = { version = "0.3.0-alpha", path = "../modules/fedimint-ln-client" }
fedimint-logging = { version = "0.3.0-alpha", path = "../fedimint-logging" }
fedimint-mint-client = { version = "0.3.0-alpha", path = "../modules/fedimint-mint-client" }
fedimint-rocksdb = { version = "0.3.0-alpha", path = "../fedimint-rocksdb" }
fedimint-wallet-client = { version = "0.3.0-alpha", path = "../modules/fedimint-wallet-client" }
futures = "0.3"
jsonrpsee-core = { version = "0.21.0", features = [ "client" ] }
jsonrpsee-types = { version = "0.21.0" }
lightning-invoice = { version = "0.27.0", features = [ "serde" ] }
rand = "0.8"
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1"
url = { version = "2.3.1", features = ["serde"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = { version = "0.21.0", features = ["webpki-tls"], default-features = false }

[build-dependencies]
fedimint-build = { version = "0.3.0-alpha", path = "../fedimint-build" }
