[package]
name = "fedimintd"
version = "0.3.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint is the main consensus code for processing transactions and REST API"
license = "MIT"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[[bin]]
name = "fedimintd"
path = "src/bin/main.rs"

[lib]
name = "fedimintd"
path = "src/lib.rs"

[dependencies]
fedimint-aead = { version = "0.3.0-alpha", path = "../crypto/aead" }
ring = "0.17.5"
anyhow = "1.0.66"
async-trait = "0.1.73"
bincode = "1.3.1"
bitcoin = "0.30.2"
bytes = "1.4.0"
hbbft = { workspace = true }
clap = { version = "4.1.6", features = ["derive", "std", "help", "usage", "error-context", "suggestions", "env"], default-features = false }
futures = "0.3.24"
itertools = "0.10.5"
jsonrpsee = { version = "0.16.2", features = ["server"] }
fedimint-bitcoind = { version = "0.3.0-alpha", path = "../fedimint-bitcoind" }
fedimint-core = { version = "0.3.0-alpha", path = "../fedimint-core" }
fedimint-ln-common = { version = "0.3.0-alpha", path = "../modules/fedimint-ln-common" }
fedimint-ln-server = { version = "0.3.0-alpha", path = "../modules/fedimint-ln-server" }
fedimint-logging = { version = "0.3.0-alpha", path = "../fedimint-logging", features = ["telemetry"] }
fedimint-metrics = { version = "0.3.0-alpha", path = "../fedimint-metrics" }
fedimint-mint-server = { version = "0.3.0-alpha", path = "../modules/fedimint-mint-server" }
fedimint-rocksdb = { version = "0.3.0-alpha", path = "../fedimint-rocksdb" }
fedimint-server = { version = "0.3.0-alpha", path = "../fedimint-server" }
fedimint-wallet-server = { version = "0.3.0-alpha", path = "../modules/fedimint-wallet-server" }
rand = "0.8"
rcgen = "=0.10.0"
secp256k1-zkp = { version = "0.9.2", features = [ "global-context", "bitcoin_hashes" ] }
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = "1.0.91"
sha3 = "0.10.5"
tbs = { package = "fedimint-tbs", version = "0.3.0-alpha", path = "../crypto/tbs" }
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tokio-rustls = "0.23.4"
tokio-util = { version = "0.7.4", features = [ "codec" ] }
tracing ="0.1.37"
url = { version = "2.3.1", features = ["serde"] }
threshold_crypto = { workspace = true }

# setup dependencies
axum = { version = "0.6.4", default-features = false, features = [ "form", "tokio" ] }
http = "0.2"
http-body = "0.4"
hyper = { version = "0.14", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
console-subscriber = "0.1.8"

[build-dependencies]
fedimint-build = { version = "0.3.0-alpha", path = "../fedimint-build" }
