[package]
name = "nostrmint-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.73"
bincode = "1.3"
fedimint-core ={ path = "../../fedimint-core" }
nostr-sdk = "0.24.0"
serde = { version = "1.0.149", features = [ "derive" ] }
schnorr_fun = { version = "0.9.1", features = ["serde", "bincode"] }
