[package]
name = "fedimint-recurringd"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-recurringd handles recurring lightning payments (e.g LNURL)"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "fedimint-recurringd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
fedimint-logging = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }

[build-dependencies]
fedimint-build = { workspace = true }
