[package]
description = "test binary for the frost crate"
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
name = "frost-playground"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "frost-playground"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
devimint = { workspace = true }
fedimint-core = { workspace = true }
frost-secp256k1-tr = "3.0.0"
miniscript = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
